### ISSUE TITLE
Types of Bot API 3.0 (released May 18, 2017)

### ISSUE THREAD

**Issue by josephpage** [telegram-bot-rb/telegram-bot-types#2]
**Are you working on it ?**
I volunteer to help. ⛑ 

Links :
- 🍾  [Changelog](https://core.telegram.org/bots/api#recent-changes)
- 💰 [Payment types](https://core.telegram.org/bots/api#payments)

**Comment by printercu** [comment]
Updated. Please check 0.4.1 out. Fill free to ping me here if you encounter an issue. Closing it for now
