### ISSUE TITLE
Undefined method `text' for Telegram::Bot::Types::ChatMemberUpdated

### ISSUE THREAD

**Issue by vrtsev** [telegram-bot-rb/telegram-bot-types#5]
Hi @printercu, I got an exception using typed responses gem
Reproduce by including TypedResponse module in the controller and then add \ remove any chat member 
Using the latest version of a gem (v 0.6.3) and dependency virtus (v 1.0)

```
> payload['text'] if payload['text'].present?

NoMethodError: undefined method `text' for #<Telegram::Bot::Types::ChatMemberUpdated:0x00007fac5912c318 ... >
      public_send(name)
      ^^^^^^^^^^^
from /usr/local/bundle/gems/virtus-1.0.5/lib/virtus/instance_methods.rb:96:in `public_send'
```

**Comment by printercu** [comment]
Hey. Thanks for reporting. Could you please try `dry-rb` version using
```
gem 'telegram-bot-types', github: 'telegram-bot-rb/telegram-bot-types', branch: 'dry'
```

If it works, I'll replace virtus with dry-rb.

**Comment by vrtsev** [comment]
@printercu thanks for the response and update. Seems your update allows now to check if typed response respond to particular method. One case I have caught when trying to access attr through :[] instead of calling method:

```
[1] pry> chat
=> #<Telegram::Bot::Types::Chat id=9999999 type="group" title="title" username=nil first_name=nil last_name=nil all_members_are_administrators=true photo=nil description=nil invite_link=nil pinned_message=nil permissions=nil slow_mode_delay=nil sticker_set_name=nil can_set_sticker_set=nil>

[2] pry> chat['username']
Dry::Struct::MissingAttributeError: Missing attribute: :username
from /usr/local/bundle/gems/dry-struct-1.4.0/lib/dry/struct.rb:137:in `block in []'

[3] pry> chat[:username]
Dry::Struct::MissingAttributeError: Missing attribute: :username
from /usr/local/bundle/gems/dry-struct-1.4.0/lib/dry/struct.rb:137:in `block in []'
```
(I have replaced some sensitive data in Chat type obj)

and at the same time I can access id through ['id']:

```
[9] pry> chat['id']
=> -101010101 # replaced

[10] pry> chat[:id]
=> -101010101 # replaced
```

Does this update allow to use both method call (.username) and attribute access ([:username]) ?

**Comment by printercu** [comment]
Hey, thanks for testing! I've pushed 1a8a7bf with a fix to the same branch. Please try it and let me know if everything works.

**Comment by vrtsev** [comment]
@printercu I have tested the update, now seems everything is ok. Thank you
